# auth-service 전용 설정
# 실제 값은 env로 주입
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:8bebdb359ea7b81bf511567372c41d74}
            client-secret: W1iQymKr201yL498596ZbAbqluIQSIzC